-- CreateTable
CREATE TABLE "SiteSettings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "homeHeroTitle" TEXT NOT NULL,
    "homeHeroDescription" TEXT NOT NULL,
    "homeHeroImageUrl" TEXT,
    "homeCommunityTitle" TEXT NOT NULL,
    "homeCommunityDescription" TEXT NOT NULL,
    "membersCount" INTEGER NOT NULL DEFAULT 0,
    "eventsCount" INTEGER NOT NULL DEFAULT 0,
    "partnersCount" INTEGER NOT NULL DEFAULT 0,
    "aboutHeroTitle" TEXT NOT NULL,
    "aboutHeroDescription" TEXT NOT NULL,
    "missionTitle" TEXT NOT NULL,
    "missionContent" TEXT NOT NULL,
    "visionTitle" TEXT NOT NULL,
    "visionContent" TEXT NOT NULL,
    "historyTitle" TEXT NOT NULL,
    "historyContent" TEXT NOT NULL,
    "commitmentTitle" TEXT NOT NULL,
    "commitmentContent" TEXT NOT NULL,
    "contactHeroTitle" TEXT NOT NULL,
    "contactHeroDescription" TEXT NOT NULL,
    "contactEmail" TEXT NOT NULL,
    "contactPhone" TEXT NOT NULL,
    "contactAddress" TEXT NOT NULL,
    "contactSchedule" TEXT NOT NULL,
    "facebookUrl" TEXT,
    "twitterUrl" TEXT,
    "linkedinUrl" TEXT,
    "instagramUrl" TEXT,
    "updatedAt" DATETIME NOT NULL
);
